import './globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Script from 'next/script'
import React from 'react'

import Provider from '@/components/provider/provider'

const pretendard = localFont({
  src: './PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Market place',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko-KR" className={pretendard.className}>
      <body className={`${pretendard.className} flex h-full items-center justify-center bg-fixed`}>
        <div className="no-scrollbar fixed h-full w-96 overflow-auto overflow-x-hidden bg-white">
          <Provider>{children}</Provider>
        </div>
        <Script src="https://cdn.iamport.kr/v1/iamport.js" />
        <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" />
      </body>
    </html>
  )
}
